# fly.toml app configuration file generated for kova on 2025-05-14T16:03:44+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kova'
primary_region = 'ams'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
